In [36]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.ensemble import ExtraTreesClassifier


In [27]:
df = pd.read_csv('./Old data sets/totalMQ_KNN-imputed.csv', sep = ',')

In [31]:
X = df.iloc[:,0:8].values
y = df.iloc[:, 8].values

array = df.values
x = array[:,0:8]
Y = array[:,8]



Feature Importance

In [37]:
# feature extraction
model = ExtraTreesClassifier(n_estimators=10)
model.fit(X, Y)
print(model.feature_importances_)

[0. 0. 0. 0. 0. 0. 0. 0.]


univariate selection

In [40]:
# feature extraction
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)
# summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[nan nan nan nan nan nan nan nan]
[[115.  23.   1.   5.]
 [107.  16.   1.   5.]
 [ 99.  17.   1.   3.]
 [102.  17.   1.   3.]
 [108.  18.   1.   3.]]


/opt/jupyterhub/anaconda/lib/python3.8/site-packages/sklearn/feature_selection/_univariate_selection.py:108: RuntimeWarning: invalid value encountered in true_divide
  msb = ssbn / float(dfbn)
