In [49]:
#import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

#import necessary modules
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

T0 = pd.read_csv('./Data for model.csv', sep=';')

# Vervolgens heb ik de data van de T0 in een dataframe gezet, zodat ik de volgende stappen kan uitvoeren
df = pd.DataFrame(data=T0)

df.dropna(subset = ["Gender"], inplace=True)
df.dropna(subset = ["Leeftijd (op testdag)"], inplace=True)
df.dropna(subset = ["AST (tijd afgerond op 0,1s)"], inplace=True)
df.dropna(subset = ["BMI"], inplace=True)
df.dropna(subset = ["Gymles"], inplace=True)
df.dropna(subset = ["Categorie"], inplace=True)


print(df.shape)
df.describe().transpose()

scaler = MinMaxScaler()


(1405, 6)


In [50]:
target_column=['Categorie']
predictors = list(set(list(df.columns))-set(target_column))
df[predictors]=df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min       25%  \
Gender                       1405.0  0.504626  0.500157  0.000000  0.000000   
Leeftijd (op testdag)        1405.0  0.880783  0.111300  0.666667  0.833333   
AST (tijd afgerond op 0,1s)  1405.0  0.256438  0.079681  0.136000  0.204545   
BMI                          1405.0  0.091822  0.027201  0.008213  0.085280   
Gymles                       1405.0  0.911174  0.182953  0.200000  0.800000   
Categorie                    1405.0  2.607829  1.008127  1.000000  2.000000   

                                  50%       75%  max  
Gender                       1.000000  1.000000  1.0  
Leeftijd (op testdag)        0.833333  1.000000  1.0  
AST (tijd afgerond op 0,1s)  0.238182  0.288182  1.0  
BMI                          0.089882  0.094891  1.0  
Gymles                       1.000000  1.000000  1.0  
Categorie                    3.000000  3.000000  5.0

In [51]:
X= df[predictors].values
X= scaler.fit_transform(X)
y =df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(983, 5)
(422, 5)


In [57]:
from sklearn.neural_network import MLPClassifier
mlp= MLPClassifier(hidden_layer_sizes=(11,170,1), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train, y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

print(y_train)

/opt/jupyterhub/anaconda/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


[[3.]
 [3.]
 [2.]
 [3.]
 [3.]
 [2.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [3.]
 [1.]
 [3.]
 [2.]
 [2.]
 [3.]
 [2.]
 [4.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [1.]
 [1.]
 [1.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [4.]
 [3.]
 [2.]
 [2.]
 [1.]
 [2.]
 [3.]
 [2.]
 [3.]
 [2.]
 [2.]
 [3.]
 [5.]
 [1.]
 [2.]
 [3.]
 [1.]
 [3.]
 [3.]
 [3.]
 [1.]
 [1.]
 [1.]
 [3.]
 [2.]
 [3.]
 [5.]
 [3.]
 [3.]
 [2.]
 [4.]
 [3.]
 [3.]
 [2.]
 [3.]
 [3.]
 [2.]
 [3.]
 [3.]
 [1.]
 [4.]
 [4.]
 [1.]
 [3.]
 [4.]
 [2.]
 [2.]
 [3.]
 [3.]
 [1.]
 [1.]
 [4.]
 [3.]
 [4.]
 [1.]
 [4.]
 [3.]
 [2.]
 [2.]
 [1.]
 [4.]
 [1.]
 [1.]
 [2.]
 [1.]
 [3.]
 [3.]
 [3.]
 [3.]
 [2.]
 [4.]
 [3.]
 [2.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [1.]
 [4.]
 [3.]
 [5.]
 [3.]
 [3.]
 [3.]
 [1.]
 [3.]
 [2.]
 [3.]
 [2.]
 [3.]
 [1.]
 [3.]
 [3.]
 [4.]
 [3.]
 [1.]
 [4.]
 [3.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [3.]
 [3.]
 [1.]
 [3.]
 [1.]
 [3.]
 [3.]
 [5.]
 [5.]
 [3.]
 [3.]
 [5.]
 [3.]
 [3.]
 [3.]
 [5.]
 [3.]
 [1.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.

In [58]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_train, predict_train))
print(classification_report(y_train, predict_train))

[[  0   0 177   0   0]
 [  0   0 195   0   0]
 [  0   0 476   0   0]
 [  0   0  98   0   0]
 [  0   0  37   0   0]]
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00       177
         2.0       0.00      0.00      0.00       195
         3.0       0.48      1.00      0.65       476
         4.0       0.00      0.00      0.00        98
         5.0       0.00      0.00      0.00        37

    accuracy                           0.48       983
   macro avg       0.10      0.20      0.13       983
weighted avg       0.23      0.48      0.32       983



/opt/jupyterhub/anaconda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [59]:
print(confusion_matrix(y_test, predict_test)


SyntaxError: unexpected EOF while parsing (<ipython-input-59-162e36288b5d>, line 1)

In [60]:
print(classification_report(y_test, predict_test))
%%javascript
Jupyter.notebook.session.delete()

              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00        81
         2.0       0.00      0.00      0.00        80
         3.0       0.48      1.00      0.65       204
         4.0       0.00      0.00      0.00        46
         5.0       0.00      0.00      0.00        11

    accuracy                           0.48       422
   macro avg       0.10      0.20      0.13       422
weighted avg       0.23      0.48      0.32       422



/opt/jupyterhub/anaconda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/jupyterhub/anaconda/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
UsageError: Line magic fu